services:
  evaluacion3:
    build: IS
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://localhost:3306/evaluacion2?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      pruebatecsuper:
        condition: service_healthy
  pruebatecsuper:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: evaluacion2
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10